### ISSUE TITLE
超哥，搞个数据库上来撒

### ISSUE THREAD

**Issue by heyjun** [overtrue/rester#4]
超哥，搞个数据库上来撒，demo里缺数据库

**Comment by overtrue** [comment]
啊？这个需要啥数据库哇，你自己随便建就好嘛

**Comment by cnphar** [comment]
超哥，真希望你能把Eloquent以及分页整合到codeigniter 里面。

**Comment by overtrue** [comment]
@cnphar 好像有人搞过哦: https://github.com/brainlabs/ci-eloquent/ :smile:

**Comment by cnphar** [comment]
谢谢了。这个好像可以分页，我试试。
